name: Main

on:
  push:
    branches: "main"
  pull_request:
    branches: "*"

jobs:
  brew:
    name: Brew
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tap
        run: brew tap ${{ github.repository }} .

      - name: Install Go
        run: brew install --overwrite go

      - name: Install Geneve
        run: brew install geneve

      - name: Try Geneve
        run: geneve version
