name: Main

on:
  push:
    branches: "main"
  pull_request:
    branches: "*"

jobs:
  brew:
    name: Brew (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["macos-10.15", "macos-11", "macos-12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tap
        run: brew tap ${{ github.repository }} .

      - name: Install Go
        run: brew install --overwrite go

      - name: Install Geneve
        run: brew install --verbose geneve

      - name: Try Geneve
        run: |
          geneve version
          if [ $(geneve version | grep "version:" | head -2 | sort | uniq | wc -l) -ne 1 ]; then \
            echo -e "\nApplication and module versions do not match"; \
            false; \
          fi
